export default `
MMMMMMMMMMMMMMMMMMMMMMWNXK00OOOOO0KXNWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNKOdlc;,',,;;,,'',,;coxOKWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMWNOd:,.........',''''..',;,';cdONWMMMMMMMMMMMMMM
MMMMMMMMMMMW0d:'.............''..''..''''''',cdKWMMMMMMMMMMMM
MMMMMMMMMW0o;,,..............','.'''..........';o0WMMMMMMMMMM
MMMMMMMMKd;''','.............','.....''......'''':xXWMMMMMMMM
MMMMMMWO:'....'..'.......'''.','.....'''....:l;.',,cOWMMMMMMM
MMMMMNx,......'.....'...::...''''....'..';:ldd:'.''.;kWMMMMMM
MMMMWx,.......''...,,.':xc.....'....,;;:ddooxx:..''.':OWMMMMM
MMMMO;........''..cd;.'x0c....'''...;odkOxdxkx;..'''';cOMMMMM
MMMXl........'c:.,kk,.;OKc'''''''..';ldkOkxxOd,...'.'..lXMMMM
MMMO,........:kl.:KO,.:0Xl....';:,.':ldkkxdxko,....''..;OMMMM
MMWx'.....cc'oKo':K0:.;0Nd'...',;,.':loxkxdolc,...,,'..,xWMMM
MMNo'....,kd'oXd';ONo.'kWO;''.....';clodkd;.;c;...,;'...dWMMM
MMWd.....,xk;cKO;'dNk'.dNK:.......';llldxo:cdd;...''....dWMMM
MMWx'.....lx;,kKl.cX0:.cXXl.......':lllododxxd:...'....,xWMMM
MMM0:.....',''dOc':00:.;0No.......':c::cloddxd:..''....cKMMMM
MMMNd'.......'loc:c0O,.,ONo.......',',:lloddxo;..'....'dWMMMM
MMMMXl'''''''',,,':ko'.,kKc'...'',,,;colloodol;'''....lXMMMMM
MMMMMKc'.......''.;c'..;kk;,,''',;;:clolloooll;'''..'cKMMMMMM
MMMMMMKl'.....''.......;o:..',,,;:::collooll:,.....'lKMMMMMMM
MMMMMMMXd,...''......'',,......',;,,;:::;;;,'.'..';dXMMMMMMMM
MMMMMMMMW0l,,;,'.',,,'''''''''''''''''''','',;;''l0WMMMMMMMMM
MMMMMMMMMMNOo;''',,''............'''''...''',,:o0NMMMMMMMMMMM
MMMMMMMMMMMMWKxc;'''''.....................,cxKWMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWKkoc;,'...........'...',cokKWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMNX0kxdolcccccclodxk0XNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMM
`
